In [1]:
import pandas as pd, numpy as np
import sys, os
from pprint import pprint
import random
from datetime import datetime, timedelta

In [2]:
import seaborn as sns
from matplotlib import pyplot as plt

In [3]:
def print_runtime():
    print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("-"*19)
print_runtime()

2021-09-14 11:17:29
-------------------

# 1. GearVN Data

In [4]:
source_path = "./Data-GEARVN.csv"
pdf_gearvn = pd.read_csv(source_path)
print(pdf_gearvn.shape)
display(pdf_gearvn.head())
print_runtime()

(9782, 28)

,ID tích hợp,Thời gian,Kho lấy hàng,Thành phố,Quận huyện,Mã sản phẩm,Ngành,Hãng,Mã chung,Mã riêng,...,Ghi chú của CSKH,Trạng thái,Chăm sóc KH,Thiếu,Thieu,DH thiếu,Ngày xác nhận,Thời gian xác nhận,Nguồn đơn hàng,Column1
0,hd211915,07-02-21 21:48,2 HCM-HHT-KD-V.2,Hồ Chí Minh,Quận Gò Vấp,CHU-LOG-G304,CHU,LOGITECH,NaN,NaN,...,thieu chuot,Thành công,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:55,0:02:04,SHOWROOMHHT,NaN
1,hd211915,07-02-21 21:48,2 HCM-HHT-KD-V.2,Hồ Chí Minh,Quận Gò Vấp,KB-COR-K63-WIRELESS-MX-RD,KB,CORSAIR,NaN,NaN,...,thieu chuot,Thành công,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:55,0:00:00,SHOWROOMHHT,NaN
2,hd211916,07-02-21 21:47,8 HCM-CQ-KD,Hồ Chí Minh,Quận 1,HDD-WD-BLUE-1TB,HDD,WD,NaN,NaN,...,NaN,Thành công,Trần Thiện Tý,-,-,-,07-02-21 21:48,0:00:00,SHOWROOMHHT,NaN
3,hd211914,07-02-21 21:42,2 HCM-HHT-KD-V.2,Bình Dương,Thị xã Tân Uyên,TAI-STE-ARCTIS-7-WHITE,TAI,STEELSERIES,NaN,NaN,...,NaN,Hệ thống hủy,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:44,0:00:00,SHOWROOMHHT,NaN
4,hd211914,07-02-21 21:42,2 HCM-HHT-KD-V.2,Bình Dương,Thị xã Tân Uyên,PK-KING-BINH-GIU-NHIET-BLK,PK,KINGSTON,NaN,NaN,...,NaN,Hệ thống hủy,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:44,0:00:00,SHOWROOMHHT,NaN

2021-09-14 11:17:37
-------------------

In [5]:
pdf_agent = pdf_gearvn[["Chăm sóc KH"]].drop_duplicates()
print(f"Number of agents: {pdf_agent.shape[0]}")
display(pdf_agent.head())

print_runtime()

Number of agents: 22

          Chăm sóc KH
0   Nguyễn Anh Nguyên
2       Trần Thiện Tý
5      Phạm Ngọc Hiếu
9         Trần Anh Vũ
12      Võ Quốc Khánh

2021-09-14 11:17:44
-------------------

In [6]:
pdf_gearvn.columns

Index(['ID tích hợp', 'Thời gian', 'Kho lấy hàng', 'Thành phố', 'Quận huyện',
       'Mã sản phẩm', 'Ngành', 'Hãng', 'Mã chung', 'Mã riêng', 'Chiết khấu',
       'Giá', 'Giá sau CK', 'Số lượng', 'Giá trị đơn hàng', 'Tiền chiết khấu',
       'Tiền đặt cọc', 'Tổng thu', 'Ghi chú của CSKH', 'Trạng thái',
       'Chăm sóc KH', 'Thiếu', 'Thieu', 'DH thiếu', 'Ngày xác nhận',
       'Thời gian xác nhận', 'Nguồn đơn hàng', 'Column1'],
      dtype='object')

In [10]:
pdf_prod = pdf_gearvn[["Ngành", "Hãng", "Mã sản phẩm", "Kho lấy hàng","Chiết khấu", 
 "Giá", "Tiền chiết khấu"]].drop_duplicates()
print(f"Number of products: {pdf_prod.shape[0]}")
display(pdf_prod.head())

print_runtime()

Number of products: 5895

,Ngành,Hãng,Mã sản phẩm,Kho lấy hàng,Chiết khấu,Giá,Tiền chiết khấu
0,CHU,LOGITECH,CHU-LOG-G304,2 HCM-HHT-KD-V.2,NaN,"790,000",NaN
1,KB,CORSAIR,KB-COR-K63-WIRELESS-MX-RD,2 HCM-HHT-KD-V.2,NaN,"2,490,000",NaN
2,HDD,WD,HDD-WD-BLUE-1TB,8 HCM-CQ-KD,NaN,"980,000",NaN
3,TAI,STEELSERIES,TAI-STE-ARCTIS-7-WHITE,2 HCM-HHT-KD-V.2,"350,000","3,990,000","350,000"
4,PK,KINGSTON,PK-KING-BINH-GIU-NHIET-BLK,2 HCM-HHT-KD-V.2,NaN,-,"350,000"

2021-09-14 11:19:59
-------------------

In [17]:
pdf_prod["Chiết khấu"].fillna(0, inplace=True)
display(pdf_prod.head())

,Ngành,Hãng,Mã sản phẩm,Kho lấy hàng,Chiết khấu,Giá,Tiền chiết khấu
0,CHU,LOGITECH,CHU-LOG-G304,2 HCM-HHT-KD-V.2,0,"790,000",0
1,KB,CORSAIR,KB-COR-K63-WIRELESS-MX-RD,2 HCM-HHT-KD-V.2,0,"2,490,000",0
2,HDD,WD,HDD-WD-BLUE-1TB,8 HCM-CQ-KD,0,"980,000",0
3,TAI,STEELSERIES,TAI-STE-ARCTIS-7-WHITE,2 HCM-HHT-KD-V.2,"350,000","3,990,000","350,000"
4,PK,KINGSTON,PK-KING-BINH-GIU-NHIET-BLK,2 HCM-HHT-KD-V.2,0,-,"350,000"

In [20]:
#Replace "," to ""
pdf_prod["Chiết khấu"].replace(to_replace =",",
                 value ="", inplace = True)
display(pdf_prod.head())

,Ngành,Hãng,Mã sản phẩm,Kho lấy hàng,Chiết khấu,Giá,Tiền chiết khấu
0,CHU,LOGITECH,CHU-LOG-G304,2 HCM-HHT-KD-V.2,0,"790,000",0
1,KB,CORSAIR,KB-COR-K63-WIRELESS-MX-RD,2 HCM-HHT-KD-V.2,0,"2,490,000",0
2,HDD,WD,HDD-WD-BLUE-1TB,8 HCM-CQ-KD,0,"980,000",0
3,TAI,STEELSERIES,TAI-STE-ARCTIS-7-WHITE,2 HCM-HHT-KD-V.2,"350,000","3,990,000","350,000"
4,PK,KINGSTON,PK-KING-BINH-GIU-NHIET-BLK,2 HCM-HHT-KD-V.2,0,-,"350,000"

In [18]:
pdf_prod["Chiết khấu"] = pdf_prod["Chiết khấu"].astype(float)

ValueError: could not convert string to float: '350,000'

In [14]:
pdf_prod["Tiền chiết khấu"].fillna(0, inplace=True)
display(pdf_prod.head())

,Ngành,Hãng,Mã sản phẩm,Kho lấy hàng,Chiết khấu,Giá,Tiền chiết khấu
0,CHU,LOGITECH,CHU-LOG-G304,2 HCM-HHT-KD-V.2,0,"790,000",0
1,KB,CORSAIR,KB-COR-K63-WIRELESS-MX-RD,2 HCM-HHT-KD-V.2,0,"2,490,000",0
2,HDD,WD,HDD-WD-BLUE-1TB,8 HCM-CQ-KD,0,"980,000",0
3,TAI,STEELSERIES,TAI-STE-ARCTIS-7-WHITE,2 HCM-HHT-KD-V.2,"350,000","3,990,000","350,000"
4,PK,KINGSTON,PK-KING-BINH-GIU-NHIET-BLK,2 HCM-HHT-KD-V.2,0,-,"350,000"

In [15]:
#Replace "-" to ""
pdf_prod["Giá"].replace(to_replace ="-",
                 value ="0", inplace = True)
display(pdf_prod.head())

,Ngành,Hãng,Mã sản phẩm,Kho lấy hàng,Chiết khấu,Giá,Tiền chiết khấu
0,CHU,LOGITECH,CHU-LOG-G304,2 HCM-HHT-KD-V.2,0,"790,000",0
1,KB,CORSAIR,KB-COR-K63-WIRELESS-MX-RD,2 HCM-HHT-KD-V.2,0,"2,490,000",0
2,HDD,WD,HDD-WD-BLUE-1TB,8 HCM-CQ-KD,0,"980,000",0
3,TAI,STEELSERIES,TAI-STE-ARCTIS-7-WHITE,2 HCM-HHT-KD-V.2,"350,000","3,990,000","350,000"
4,PK,KINGSTON,PK-KING-BINH-GIU-NHIET-BLK,2 HCM-HHT-KD-V.2,0,-,"350,000"