In [1]:
import pandas as pd, numpy as np
import sys, os
from pprint import pprint
import random
from datetime import datetime, timedelta

In [2]:
import seaborn as sns
from matplotlib import pyplot as plt

In [3]:
def print_runtime():
    print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("-"*19)
print_runtime()

2021-09-28 13:05:59
-------------------

# 1. GearVN Data

In [4]:
source_path = "./Data-GEARVN.csv"
pdf_gearvn = pd.read_csv(source_path)
print(pdf_gearvn.shape)
display(pdf_gearvn.head())
print_runtime()

(9782, 28)

,ID tích hợp,Thời gian,Kho lấy hàng,Thành phố,Quận huyện,Mã sản phẩm,Ngành,Hãng,Mã chung,Mã riêng,...,Ghi chú của CSKH,Trạng thái,Chăm sóc KH,Thiếu,Thieu,DH thiếu,Ngày xác nhận,Thời gian xác nhận,Nguồn đơn hàng,Column1
0,hd211915,07-02-21 21:48,2 HCM-HHT-KD-V.2,Hồ Chí Minh,Quận Gò Vấp,CHU-LOG-G304,CHU,LOGITECH,NaN,NaN,...,thieu chuot,Thành công,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:55,0:02:04,SHOWROOMHHT,NaN
1,hd211915,07-02-21 21:48,2 HCM-HHT-KD-V.2,Hồ Chí Minh,Quận Gò Vấp,KB-COR-K63-WIRELESS-MX-RD,KB,CORSAIR,NaN,NaN,...,thieu chuot,Thành công,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:55,0:00:00,SHOWROOMHHT,NaN
2,hd211916,07-02-21 21:47,8 HCM-CQ-KD,Hồ Chí Minh,Quận 1,HDD-WD-BLUE-1TB,HDD,WD,NaN,NaN,...,NaN,Thành công,Trần Thiện Tý,-,-,-,07-02-21 21:48,0:00:00,SHOWROOMHHT,NaN
3,hd211914,07-02-21 21:42,2 HCM-HHT-KD-V.2,Bình Dương,Thị xã Tân Uyên,TAI-STE-ARCTIS-7-WHITE,TAI,STEELSERIES,NaN,NaN,...,NaN,Hệ thống hủy,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:44,0:00:00,SHOWROOMHHT,NaN
4,hd211914,07-02-21 21:42,2 HCM-HHT-KD-V.2,Bình Dương,Thị xã Tân Uyên,PK-KING-BINH-GIU-NHIET-BLK,PK,KINGSTON,NaN,NaN,...,NaN,Hệ thống hủy,Nguyễn Anh Nguyên,-,-,-,07-02-21 21:44,0:00:00,SHOWROOMHHT,NaN

2021-09-28 13:05:59
-------------------

In [5]:
pdf_gearvn[["ID", "Modified"]] = pdf_gearvn["ID tích hợp"].str.split("-", expand=True)
pdf_gearvn["Modified"] = pdf_gearvn["Modified"].fillna(0).astype(int)
display(pdf_gearvn[["ID tích hợp", "ID", "Modified"]].head())
print_runtime()

  ID tích hợp        ID  Modified
0    hd211915  hd211915         0
1    hd211915  hd211915         0
2    hd211916  hd211916         0
3    hd211914  hd211914         0
4    hd211914  hd211914         0

2021-09-28 13:05:59
-------------------

In [6]:
pdf_gearvn.dtypes

ID tích hợp            object
Thời gian              object
Kho lấy hàng           object
Thành phố              object
Quận huyện             object
Mã sản phẩm            object
Ngành                  object
Hãng                   object
Mã chung               object
Mã riêng               object
Chiết khấu             object
Giá                    object
Giá sau CK             object
Số lượng                int64
Giá trị đơn hàng       object
Tiền chiết khấu        object
Tiền đặt cọc          float64
Tổng thu               object
Ghi chú của CSKH       object
Trạng thái             object
Chăm sóc KH            object
Thiếu                  object
Thieu                  object
DH thiếu               object
Ngày xác nhận          object
Thời gian xác nhận     object
Nguồn đơn hàng         object
Column1               float64
ID                     object
Modified                int32
dtype: object

In [7]:
display(
    pdf_gearvn
    [(pdf_gearvn["Modified"]>1)]
    [["ID tích hợp", "ID", "Modified"]]
    .head()
)

print_runtime()

    ID tích hợp        ID  Modified
121  hd203913-3  hd203913         3
122  hd203913-3  hd203913         3
123  hd203913-3  hd203913         3
124  hd203913-3  hd203913         3
125  hd203913-3  hd203913         3

2021-09-28 13:05:59
-------------------

In [8]:
pdf_gearvn["Chăm sóc KH"] = pdf_gearvn["Chăm sóc KH"].str.upper()

In [9]:
pdf_agent = pdf_gearvn[["Chăm sóc KH"]].drop_duplicates().dropna()
print(f"Number of agents: {pdf_agent.shape[0]}")
display(pdf_agent.head())

print_runtime()

Number of agents: 21

          Chăm sóc KH
0   NGUYỄN ANH NGUYÊN
2       TRẦN THIỆN TÝ
5      PHẠM NGỌC HIẾU
9         TRẦN ANH VŨ
12      VÕ QUỐC KHÁNH

2021-09-28 13:05:59
-------------------

In [10]:
pdf_gearvn.columns

Index(['ID tích hợp', 'Thời gian', 'Kho lấy hàng', 'Thành phố', 'Quận huyện',
       'Mã sản phẩm', 'Ngành', 'Hãng', 'Mã chung', 'Mã riêng', 'Chiết khấu',
       'Giá', 'Giá sau CK', 'Số lượng', 'Giá trị đơn hàng', 'Tiền chiết khấu',
       'Tiền đặt cọc', 'Tổng thu', 'Ghi chú của CSKH', 'Trạng thái',
       'Chăm sóc KH', 'Thiếu', 'Thieu', 'DH thiếu', 'Ngày xác nhận',
       'Thời gian xác nhận', 'Nguồn đơn hàng', 'Column1', 'ID', 'Modified'],
      dtype='object')

In [11]:
pdf_gearvn["Trạng thái"].unique()

array(['Thành công', 'Hệ thống hủy', 'Đã xác nhận', 'Đang xác nhận'],
      dtype=object)

# Products

# Question:
- Should we put "Chiết khấu" and "Tiền chiết khấu" into pdf_prod?

In [12]:
# Consider another option
# ls_prod_col = ["Ngành", "Hãng", "Mã sản phẩm", "Giá"]
pdf_prod = pdf_gearvn[[
    "Ngành", "Hãng", "Mã sản phẩm", "Giá"
    # , "Chiết khấu", "Tiền chiết khấu", "Kho lấy hàng"
    ]].drop_duplicates()
print(f"Number of products: {pdf_prod.shape[0]}")
display(pdf_prod.head())

print_runtime()

Number of products: 1166

  Ngành         Hãng                 Mã sản phẩm        Giá
0   CHU     LOGITECH                CHU-LOG-G304    790,000
1    KB      CORSAIR   KB-COR-K63-WIRELESS-MX-RD  2,490,000
2   HDD           WD             HDD-WD-BLUE-1TB    980,000
3   TAI  STEELSERIES      TAI-STE-ARCTIS-7-WHITE  3,990,000
4    PK     KINGSTON  PK-KING-BINH-GIU-NHIET-BLK       -

2021-09-28 13:05:59
-------------------

- All the Logitech mice G304 have the same price 790000, although they have different "Discount" and "Total discount"
- We can assume that "Total discount" and "Discount" are belong to pdf_orders or pdf_order_details, where "Total discount" is applied for the whole order while "Discount" is "Total discount" divided by number of products.
- If the policy is that, the mouse and kb are calculated in the total price, but then covered by the discount, we can add another column to compare between "Total discount", "Mouse and kb". If they're all matched in the orders which contained both PC parts and gears, then we have a way to compare package included / separated sales for GEAR.

In [13]:
display(pdf_prod[
    (pdf_prod["Ngành"]=="CHU")
    & (pdf_prod["Hãng"]=="LOGITECH")
    & (pdf_prod["Mã sản phẩm"]=="CHU-LOG-G304")
])

  Ngành      Hãng   Mã sản phẩm      Giá
0   CHU  LOGITECH  CHU-LOG-G304  790,000

In [14]:
pdf_prod[
    (pdf_prod["Ngành"]=="KB")
    & (pdf_prod["Hãng"]=="CORSAIR")
    & (pdf_prod["Mã sản phẩm"]=="KB-COR-K63-WIRELESS-MX-RD")
]

  Ngành     Hãng                Mã sản phẩm        Giá
1    KB  CORSAIR  KB-COR-K63-WIRELESS-MX-RD  2,490,000

In [15]:
# Convert Giá, Chiết khấu, Tiền chiết khấu to int

In [16]:
pdf_gearvn["Chiết khấu"] = (
    pdf_gearvn["Chiết khấu"].str.replace(",", "")
    .fillna(0.0)
    .astype(int)
)

pdf_gearvn["Tiền chiết khấu"] = (
    pdf_gearvn["Tiền chiết khấu"].str.replace(",", "")
    .fillna(0.0)
    .astype(int)
)
pdf_gearvn["Giá"] = (
    pdf_gearvn["Giá"].str.replace(",", "").replace(" -   ", "0")
    .fillna(0.0)
    .astype(int)
)

In [17]:

pdf_gearvn["Giá trị đơn hàng"] = (
    pdf_gearvn["Giá trị đơn hàng"].str.replace(",", "").replace(" -   ", "0")
    .fillna(0.0)
    .astype(int)
)

pdf_gearvn["Tổng thu"] = (
    pdf_gearvn["Tổng thu"].str.replace(",", "").replace(" -   ", "0")
    .fillna(0.0)
    .astype(int)
)

In [18]:
pdf_gearvn[
    (pdf_gearvn["Trạng thái"].str.contains("Hệ thống")) # Return list of indexes where `Trang thai` contains "He thong huy"
    & (pdf_gearvn["Ngành"]=="TAI")  # List of indexes where `Nganh` == `TAI`
    # & => Combine 2 (or more) list of indexes
    
].head()

,ID tích hợp,Thời gian,Kho lấy hàng,Thành phố,Quận huyện,Mã sản phẩm,Ngành,Hãng,Mã chung,Mã riêng,...,Chăm sóc KH,Thiếu,Thieu,DH thiếu,Ngày xác nhận,Thời gian xác nhận,Nguồn đơn hàng,Column1,ID,Modified
3,hd211914,07-02-21 21:42,2 HCM-HHT-KD-V.2,Bình Dương,Thị xã Tân Uyên,TAI-STE-ARCTIS-7-WHITE,TAI,STEELSERIES,NaN,NaN,...,NGUYỄN ANH NGUYÊN,-,-,-,07-02-21 21:44,0:00:00,SHOWROOMHHT,NaN,hd211914,0
91,hd211894,07-02-21 20:53,2 HCM-HHT-KD-V.2,Hồ Chí Minh,huyện Củ Chi,TAI-DAR-EH416-RGB,TAI,DAREU,NaN,NaN,...,NaN,-,-,-,NaN,0:10:10,TELEPHONE,NaN,hd211894,0
154,hd211877,07-02-21 19:57,3 HCM-HVT-KD,Hồ Chí Minh,huyện Củ Chi,TAI-DAR-EH925-PRO-RGB,TAI,DAREU,NaN,NaN,...,TRẦN ANH VŨ,-,-,-,07-02-21 19:59,0:01:53,SHOWROOMHHT,NaN,hd211877,0
155,hd211875,07-02-21 19:56,2 HCM-HHT-KD-V.2,Hồ Chí Minh,Quận Gò Vấp,TAI-PAM-PADMATE-SLIDE-PLUS-GRN,TAI,PAMU,NaN,NaN,...,NGUYỄN CAO THẮNG,-,-,-,07-02-21 19:58,0:01:53,OTHER,NaN,hd211875,0
320,hd211814,07-02-21 18:12,3 HCM-HVT-KD,NaN,NaN,TAI-RAZ-BLACK-SHARK-V2-X,TAI,RAZER,NaN,NaN,...,TRẦN ANH VŨ,-,-,-,08-02-21 8:18,0:18:15,HARAVAN,NaN,hd211814,0

In [19]:
display(pdf_gearvn[["Giá","Chiết khấu","Tiền chiết khấu"]].head(10))

       Giá  Chiết khấu  Tiền chiết khấu
0   790000           0                0
1  2490000           0                0
2   980000           0                0
3  3990000      350000           350000
4        0           0           350000
5  1490000           0                0
6  1520000           0                0
7  1490000           0                0
8  2790000           0                0
9   435000           0                0

In [20]:
pdf_gearvn.dtypes

ID tích hợp            object
Thời gian              object
Kho lấy hàng           object
Thành phố              object
Quận huyện             object
Mã sản phẩm            object
Ngành                  object
Hãng                   object
Mã chung               object
Mã riêng               object
Chiết khấu              int32
Giá                     int32
Giá sau CK             object
Số lượng                int64
Giá trị đơn hàng        int32
Tiền chiết khấu         int32
Tiền đặt cọc          float64
Tổng thu                int32
Ghi chú của CSKH       object
Trạng thái             object
Chăm sóc KH            object
Thiếu                  object
Thieu                  object
DH thiếu               object
Ngày xác nhận          object
Thời gian xác nhận     object
Nguồn đơn hàng         object
Column1               float64
ID                     object
Modified                int32
dtype: object

# Order and order detail

In [21]:
pdf_gearvn.columns

Index(['ID tích hợp', 'Thời gian', 'Kho lấy hàng', 'Thành phố', 'Quận huyện',
       'Mã sản phẩm', 'Ngành', 'Hãng', 'Mã chung', 'Mã riêng', 'Chiết khấu',
       'Giá', 'Giá sau CK', 'Số lượng', 'Giá trị đơn hàng', 'Tiền chiết khấu',
       'Tiền đặt cọc', 'Tổng thu', 'Ghi chú của CSKH', 'Trạng thái',
       'Chăm sóc KH', 'Thiếu', 'Thieu', 'DH thiếu', 'Ngày xác nhận',
       'Thời gian xác nhận', 'Nguồn đơn hàng', 'Column1', 'ID', 'Modified'],
      dtype='object')

In [22]:
ls_num_col = {
    "Giá trị đơn hàng": 0.0, "Tiền chiết khấu": 0.0, 
    "Tiền đặt cọc": 0.0, "Tổng thu": 0.0
}
ls_str_col = {
    "Thời gian": "", "Ghi chú của CSKH": "", "Trạng thái": "", "Chăm sóc KH": "",
    "Thiếu": "", "Thieu": "", "DH thiếu": "",
    "Ngày xác nhận": "","Nguồn đơn hàng": ""
}
pdf_order = (
    pdf_gearvn[[
        "ID tích hợp", "ID", "Modified",
        "Thời gian", # Sales created order
        "Giá trị đơn hàng", "Tiền chiết khấu", "Tiền đặt cọc", "Tổng thu",
        "Ghi chú của CSKH", "Trạng thái", "Chăm sóc KH", "Thiếu", "Thieu", "DH thiếu", 
        "Ngày xác nhận", # Storage confirmed timestamp
        "Nguồn đơn hàng",]]
    .fillna(ls_num_col)
    .fillna(ls_str_col)
    .groupby(["ID tích hợp", "ID", "Modified"], as_index=False).agg({
        "Thời gian": "max", 
        "Giá trị đơn hàng": "max", 
        "Tiền chiết khấu": "max", 
        "Tiền đặt cọc": "max", 
        "Tổng thu": "max",
        "Ghi chú của CSKH": "max", 
        "Trạng thái": "max", 
        "Chăm sóc KH": "max", 
        "Thiếu": "max", 
        "Thieu": "max", 
        "DH thiếu": "max", 
        "Ngày xác nhận": "max", 
        "Nguồn đơn hàng": "max"
    })
)

print(f"Number of order: {pdf_order.shape[0]}")
display(pdf_order.head())

print_runtime()

Number of order: 3400

,ID tích hợp,ID,Modified,Thời gian,Giá trị đơn hàng,Tiền chiết khấu,Tiền đặt cọc,Tổng thu,Ghi chú của CSKH,Trạng thái,Chăm sóc KH,Thiếu,Thieu,DH thiếu,Ngày xác nhận,Nguồn đơn hàng
0,hd108850-9,hd108850,9,05-02-21 19:46,294000000,0,0.0,294000000,,Hệ thống hủy,NGUYỄN ANH TUẤN,1,-,1,06-02-21 7:58,OTHER
1,hd170656-6,hd170656,6,06-02-21 18:11,193500000,1270000,0.0,193500000,,Hệ thống hủy,NGUYỄN THẾ VINH,-,-,-,06-02-21 18:17,OTHER
2,hd203577-1,hd203577,1,01-02-21 8:11,17830000,0,0.0,17830000,,Thành công,NGUYỄN THẾ NAM,-,-,-,02-02-21 12:52,SHOWROOMHHT
3,hd203879-1,hd203879,1,01-02-21 8:43,0,9000000,0.0,0,,Thành công,LÊ QUANG HOÀNG DŨNG,-,-,-,02-04-21 9:05,SHOWROOMHHT
4,hd203913-2,hd203913,2,05-02-21 18:41,147250003,4329997,0.0,147250003,,Hệ thống hủy,,-,-,-,,OTHER

2021-09-28 13:06:03
-------------------

In [23]:
# display(pdf_order[pdf_order['ID tích hợp'] == 'hd210706'])

In [24]:
pdf_order= pdf_order[pdf_order["Trạng thái"]=="Thành công"]
print(f"Number of order: {pdf_order.shape[0]}")
display(pdf_order.head())

print_runtime()

Number of order: 3016

,ID tích hợp,ID,Modified,Thời gian,Giá trị đơn hàng,Tiền chiết khấu,Tiền đặt cọc,Tổng thu,Ghi chú của CSKH,Trạng thái,Chăm sóc KH,Thiếu,Thieu,DH thiếu,Ngày xác nhận,Nguồn đơn hàng
2,hd203577-1,hd203577,1,01-02-21 8:11,17830000,0,0.0,17830000,,Thành công,NGUYỄN THẾ NAM,-,-,-,02-02-21 12:52,SHOWROOMHHT
3,hd203879-1,hd203879,1,01-02-21 8:43,0,9000000,0.0,0,,Thành công,LÊ QUANG HOÀNG DŨNG,-,-,-,02-04-21 9:05,SHOWROOMHHT
5,hd203913-3,hd203913,3,07-02-21 20:08,147749999,4330001,0.0,147749999,,Thành công,NGUYỄN THẾ NAM,-,-,-,08-02-21 9:24,OTHER
7,hd203974-3,hd203974,3,02-02-21 19:18,135970000,5500000,0.0,135970000,,Thành công,NGUYỄN NGỌC CHI,-,-,-,26-02-21 14:33,OTHER
8,hd204451,hd204451,0,05-02-21 15:52,16610000,1070000,0.0,16610000,,Thành công,VÕ NGỌC HẢI,-,-,-,05-02-21 16:00,HARAVAN

2021-09-28 13:06:03
-------------------

In [25]:
pdf_order.dtypes

ID tích hợp          object
ID                   object
Modified              int64
Thời gian            object
Giá trị đơn hàng      int32
Tiền chiết khấu       int32
Tiền đặt cọc        float64
Tổng thu              int32
Ghi chú của CSKH     object
Trạng thái           object
Chăm sóc KH          object
Thiếu                object
Thieu                object
DH thiếu             object
Ngày xác nhận        object
Nguồn đơn hàng       object
dtype: object

### Need to clear the relationship between "Chiết khấu", "Giá", "Giá sau CK" as some records showed inconsistent value

In [26]:
pdf_gearvn.columns

Index(['ID tích hợp', 'Thời gian', 'Kho lấy hàng', 'Thành phố', 'Quận huyện',
       'Mã sản phẩm', 'Ngành', 'Hãng', 'Mã chung', 'Mã riêng', 'Chiết khấu',
       'Giá', 'Giá sau CK', 'Số lượng', 'Giá trị đơn hàng', 'Tiền chiết khấu',
       'Tiền đặt cọc', 'Tổng thu', 'Ghi chú của CSKH', 'Trạng thái',
       'Chăm sóc KH', 'Thiếu', 'Thieu', 'DH thiếu', 'Ngày xác nhận',
       'Thời gian xác nhận', 'Nguồn đơn hàng', 'Column1', 'ID', 'Modified'],
      dtype='object')

In [27]:
ls_od_col = [
    "ID tích hợp", "Mã sản phẩm", "Ngành", "Số lượng", "Chiết khấu", "Giá",
    "ID", "Modified", 'Chăm sóc KH'
]

pdf_orderdetail = pdf_gearvn[pdf_gearvn["Trạng thái"]=="Thành công"][ls_od_col]
display(pdf_orderdetail.head())
print_runtime()

,ID tích hợp,Mã sản phẩm,Ngành,Số lượng,Chiết khấu,Giá,ID,Modified,Chăm sóc KH
0,hd211915,CHU-LOG-G304,CHU,1,0,790000,hd211915,0,NGUYỄN ANH NGUYÊN
1,hd211915,KB-COR-K63-WIRELESS-MX-RD,KB,1,0,2490000,hd211915,0,NGUYỄN ANH NGUYÊN
2,hd211916,HDD-WD-BLUE-1TB,HDD,1,0,980000,hd211916,0,TRẦN THIỆN TÝ
5,hd211912,CHU-ZOW-BENQ-S1,CHU,1,0,1490000,hd211912,0,PHẠM NGỌC HIẾU
6,hd211911,KB-AKKO-DRAGONBALL-ACG84-AKKO-PINK,KB,1,0,1520000,hd211911,0,NGUYỄN ANH NGUYÊN

2021-09-28 13:06:03
-------------------

In [28]:
pdf_orderdetail['Giá sau CK'] = pdf_orderdetail['Giá'] - pdf_orderdetail['Chiết khấu']
display(pdf_orderdetail.head())
print_runtime()

,ID tích hợp,Mã sản phẩm,Ngành,Số lượng,Chiết khấu,Giá,ID,Modified,Chăm sóc KH,Giá sau CK
0,hd211915,CHU-LOG-G304,CHU,1,0,790000,hd211915,0,NGUYỄN ANH NGUYÊN,790000
1,hd211915,KB-COR-K63-WIRELESS-MX-RD,KB,1,0,2490000,hd211915,0,NGUYỄN ANH NGUYÊN,2490000
2,hd211916,HDD-WD-BLUE-1TB,HDD,1,0,980000,hd211916,0,TRẦN THIỆN TÝ,980000
5,hd211912,CHU-ZOW-BENQ-S1,CHU,1,0,1490000,hd211912,0,PHẠM NGỌC HIẾU,1490000
6,hd211911,KB-AKKO-DRAGONBALL-ACG84-AKKO-PINK,KB,1,0,1520000,hd211911,0,NGUYỄN ANH NGUYÊN,1520000

2021-09-28 13:06:03
-------------------

In [29]:
pdf_orderdetail.shape

(7612, 10)

# Group by ID: Only orders with "Trạng thái" == "Thành công"
# Separated data into
pdf_prod: Finalized => Save to csv/pickle file
  pdf_prod.to_pickle(filename)
pdf_order
pdf_orderdetail

## HW0: Create new column "Giá sau CK" = "Giá" - "Chiết khấu"

# Question 1. 
- Tính tỉ trọng đơn hàng Online và Offline trên doanh thu tổng của ngành hàng
- Theo GEARVN quy định, Sales của bộ phận Showroom lên đơn sẽ tính là đơn hàng Offline, áp dụng tương tự với Online.
- pdf_agent["Chăm sóc KH", "IS_ONLINE"]
- pdf_gearvn.join(pdf_agent, on="Chăm sóc KH", how="inner")
=> pdf_prod, pdf_order, pdf_orderdetail 
## HW1: Only get Sucessful order
pdf_orderdetail.groupby("IS_ONLINE").agg(
    "Giá sau CK": "sum"
)

# Question 2. Xác định tỉ trọng sản phẩm Gaming Gear bán lẻ và sản phẩm Gaming Gear được bán cùng PC/Monitor
- Gaming Gear bán lẻ: Chiết khấu = 0
- Bán kèm: Chiết khấu !=0
pdf_gearvn["with_pc"] = (pdf_gearvn["Chiết khấu"] != 0).astype(int)

- Separate Gaming Gear only
  - Method 1:
pdf_gaming_gear = pdf_gearvn[
    (pdf_gearvn["Ngành]=="TAI")
    | (pdf_gearvn["Ngành]=="CHU")
    | (pdf_gearvn["Ngành]=="KB")]
]
  - Method 2:
pdf_gaming_gear = pdf_gearvn[
    pdf_gearvn["Ngành].isin(["TAI", "CHU", "KB"])
]
## HW2: Compare "Giá" vs. "Giá sau CK"
pdf_gg_compare = (
    pdf_gaming_gear
    .groupby("with_pc", as_index=False)
    .agg({"Giá sau CK": "sum"})
)

# Answer Question 1

In [30]:
sales_gearvn = pd.read_excel('Agent.xlsx')
print(sales_gearvn.shape)
display(sales_gearvn.head())
print_runtime()

(14, 2)

            Showroom           Online
0  Nguyễn Anh Nguyên    Trần Thiện Tý
1     Phạm Ngọc Hiếu  Nguyễn Thế Vinh
2        Trần Anh Vũ   Nguyễn Thế Nam
3      Võ Quốc Khánh  Nguyễn Anh Tuấn
4  Nguyễn Đinh Thuận     Trần Anh Hào

2021-09-28 13:06:04
-------------------

In [31]:
agent_onl = sales_gearvn['Online'].str.upper().dropna() 
display(agent_onl)
print_runtime()

0        TRẦN THIỆN TÝ
1      NGUYỄN THẾ VINH
2       NGUYỄN THẾ NAM
3      NGUYỄN ANH TUẤN
4         TRẦN ANH HÀO
5     NGUYỄN MINH HIẾU
6    NGUYỄN HOÀN THIỆN
Name: Online, dtype: object

2021-09-28 13:06:04
-------------------

In [32]:
onl_order = (pdf_order[pdf_order['Chăm sóc KH'].isin(agent_onl)])['Chăm sóc KH'].count() #Number of online orders
onl_order_ratio = onl_order / pdf_order['Chăm sóc KH'].count() 
print(onl_order_ratio)

0.32161803713527853

# Answer Question 2

In [33]:
ls_col= ["ID tích hợp", "ID", "Modified", "Ngành", "Giá","Chiết khấu"]
pdf_categories = pdf_gearvn[pdf_gearvn["Trạng thái"]=="Thành công"][ls_col]
display(pdf_categories.head())
print(pdf_categories.shape)

  ID tích hợp        ID  Modified Ngành      Giá  Chiết khấu
0    hd211915  hd211915         0   CHU   790000           0
1    hd211915  hd211915         0    KB  2490000           0
2    hd211916  hd211916         0   HDD   980000           0
5    hd211912  hd211912         0   CHU  1490000           0
6    hd211911  hd211911         0    KB  1520000           0

(7612, 6)

In [34]:
pdf_categories["Giá sau CK"] = pdf_categories["Giá"] - pdf_categories["Chiết khấu"]

In [35]:
pdf_gaming_gear = pdf_categories[(pdf_categories["Ngành"] == "CHU")
                                 | (pdf_categories["Ngành"] == "KB")
                                 | (pdf_categories["Ngành"] == "TAI")
                                ]
pdf_gaming_gear.head()
# pdf_gaming_gear[pdf_gaming_gear["Ngành"] == 'KB']
# print_runtime()

   ID tích hợp        ID  Modified Ngành      Giá  Chiết khấu  Giá sau CK
0     hd211915  hd211915         0   CHU   790000           0      790000
1     hd211915  hd211915         0    KB  2490000           0     2490000
5     hd211912  hd211912         0   CHU  1490000           0     1490000
6     hd211911  hd211911         0    KB  1520000           0     1520000
10    hd211910  hd211910         0   TAI   340000           0      340000

In [36]:
gaming_gear_orders = pd.DataFrame(pdf_gaming_gear.groupby('ID')['Chiết khấu'].max())
display(gaming_gear_orders.head())
print(gaming_gear_orders.shape)

          Chiết khấu
ID
hd203974           0
hd204575           0
hd204766           0
hd206043           0
hd207316           0

(1824, 1)

In [37]:
gaming_gear_orders.count()

Chiết khấu    1824
dtype: int64

In [38]:
separate_gaming_gear = (gaming_gear_orders[gaming_gear_orders['Chiết khấu'] == 0 ])['Chiết khấu'].count()

In [39]:
separate_gaming_gear_ratio = separate_gaming_gear / (gaming_gear_orders.count())
print(separate_gaming_gear_ratio)

Chiết khấu    0.948465
dtype: float64

# Question 3

### Find out a particular sold product (Gaming Gear)
### Find out the numbers of sold products in the same purchase with PC
### Find out the numbers of sold products in the same purchase with Laptop

In [77]:
x = str(input('Fill Product Name: '))
print(x)

Fill Product Name: CHU-LOG-G402
CHU-LOG-G402

In [78]:
pdf_gg = pdf_orderdetail[(pdf_orderdetail["Mã sản phẩm"] == x)]
display(pdf_gg.head())
print(pdf_gg.shape)

,ID tích hợp,Mã sản phẩm,Ngành,Số lượng,Chiết khấu,Giá,ID,Modified,Chăm sóc KH,Giá sau CK
225,hd211820-1,CHU-LOG-G402,CHU,1,0,0,hd211820,1,NGUYỄN CAO THẮNG,0
1405,hd211472,CHU-LOG-G402,CHU,1,94920,640000,hd211472,0,TRẦN THIỆN TÝ,545080
1496,hd211444,CHU-LOG-G402,CHU,1,24520,640000,hd211444,0,NGUYỄN ĐINH THUẬN,615480
1574,hd211407,CHU-LOG-G402,CHU,1,0,640000,hd211407,0,VÕ QUỐC KHÁNH,640000
1632,hd211370,CHU-LOG-G402,CHU,1,0,640000,hd211370,0,TRẦN ANH HÀO,640000

(30, 10)

In [79]:
#Numbers of product sold
numbers_gg_sold = pdf_gg.shape[0]

In [80]:
pdf_lap = pdf_orderdetail[(pdf_orderdetail["Ngành"] == 'LAP')]
display(pdf_lap.head())
print(pdf_lap.shape)

,ID tích hợp,Mã sản phẩm,Ngành,Số lượng,Chiết khấu,Giá,ID,Modified,Chăm sóc KH,Giá sau CK
51,hd211874,LAP-ACER-A715-41G-R282,LAP,1,3300000,19990000,hd211874,0,NGUYỄN ANH NGUYÊN,16690000
211,hd211847,LAP-ACER-AN515-55-77P9,LAP,1,5300698,28990000,hd211847,0,NGUYỄN ĐỨC QUANG,23689302
223,hd211820-1,LAP-ASU-FA506II-AL012T,LAP,1,200000,21990000,hd211820,1,NGUYỄN CAO THẮNG,21790000
229,hd211843,LAP-ACER-AN515-55-77P9,LAP,1,5300698,28990000,hd211843,0,TRẦN THIỆN TÝ,23689302
406,hd211785,LAP-ASU-B9450FA-BM0616R,LAP,1,0,27990000,hd211785,0,VÕ QUỐC KHÁNH,27990000

(177, 10)

In [81]:
ls_col_lap_gg = ['ID tích hợp', 'Mã sản phẩm_gg', 'Mã sản phẩm_lap', 'Số lượng_gg', 'Số lượng_lap']
pdf_lap_with_gg = (pdf_gg.merge(pdf_lap, on = 'ID tích hợp', how = 'left', suffixes = ('_gg','_lap')))[ls_col_lap_gg]
display(pdf_lap_with_gg.head())
print(pdf_lap_with_gg.shape)

,ID tích hợp,Mã sản phẩm_gg,Mã sản phẩm_lap,Số lượng_gg,Số lượng_lap
0,hd211820-1,CHU-LOG-G402,LAP-ASU-FA506II-AL012T,1,1.0
1,hd211472,CHU-LOG-G402,LAP-ACER-AN515-55-5923,1,1.0
2,hd211444,CHU-LOG-G402,NaN,1,NaN
3,hd211407,CHU-LOG-G402,NaN,1,NaN
4,hd211370,CHU-LOG-G402,NaN,1,NaN

(30, 5)

In [82]:
ls_col_pc = ['ID tích hợp','Số lượng_mb']
pdf_cpu = pdf_orderdetail[(pdf_orderdetail["Ngành"] == 'CPU')]
pdf_mb = pdf_orderdetail[(pdf_orderdetail["Ngành"] == 'MB')]
pdf_psu = pdf_orderdetail[(pdf_orderdetail["Ngành"] == 'PW')]
pdf_pc = (pdf_cpu.merge(pdf_mb, on = 'ID tích hợp', how = 'inner', suffixes=('_cpu','_mb'))
          .merge(pdf_psu,on = 'ID tích hợp', how = 'inner'))\
[ls_col_pc]
pdf_pc.columns = ['ID tích hợp','Số lượng_pc']
display(pdf_pc.head())
print(pdf_pc.shape)

  ID tích hợp  Số lượng_pc
0    hd211884            1
1    hd211891            1
2  hd211894-1            1
3  hd203913-3            1
4  hd211800-1            1

(395, 2)

In [83]:
ls_col_pc_gg = ['ID tích hợp', 'Mã sản phẩm_gg', 'Mã sản phẩm_pc', 'Ngành_gg', 'Ngành_pc', 'Số lượng_gg', 'Số lượng_pc']
pdf_pc_lap_with_gg = pdf_lap_with_gg.merge(pdf_pc, on = 'ID tích hợp', how = 'left', suffixes = ('_gg','_lap'))

display(pdf_pc_lap_with_gg.head())
print(pdf_pc_lap_with_gg.shape)

,ID tích hợp,Mã sản phẩm_gg,Mã sản phẩm_lap,Số lượng_gg,Số lượng_lap,Số lượng_pc
0,hd211820-1,CHU-LOG-G402,LAP-ASU-FA506II-AL012T,1,1.0,NaN
1,hd211472,CHU-LOG-G402,LAP-ACER-AN515-55-5923,1,1.0,NaN
2,hd211444,CHU-LOG-G402,NaN,1,NaN,1.0
3,hd211407,CHU-LOG-G402,NaN,1,NaN,NaN
4,hd211370,CHU-LOG-G402,NaN,1,NaN,NaN

(30, 6)

In [97]:
lap_with_gg_ratio = (pdf_pc_lap_with_gg['Số lượng_lap'].sum()) / numbers_gg_sold *100
pc_with_gg_ratio = (pdf_pc_lap_with_gg['Số lượng_pc'].sum()) / numbers_gg_sold *100
only_gg_ratio = 100 - lap_with_gg_ratio - pc_with_gg_ratio
print('Gaming Gear with Laptop Ratio: {:.2f}%'.format(lap_with_gg_ratio))
print('Gaming Gear with PC Ratio: {:.2f}%'.format(pc_with_gg_ratio))
print('Only Gaming Gear Ratio: {:.2f}%'.format(only_gg_ratio))

Gaming Gear with Laptop Ratio: 23.33%
Gaming Gear with PC Ratio: 23.33%
Only Gaming Gear Ratio: 53.33%